### ISSUE TITLE
Add support for different dependency lifetime

### ISSUE THREAD

**Issue by msmolka** [Hawxy/Auth0Net.DependencyInjection#14]
I would like to have singleton for authentication client as in most cases never changed during application lifetime.

**Comment by Hawxy** [comment]
This isn't considered good practice as we're using the `IHttpClientFactory` pattern. The client is designed to be short-lived as the internal handler is pooled. See https://learn.microsoft.com/en-us/dotnet/core/extensions/httpclient-factory#httpclient-lifetime-management

**Comment by msmolka** [comment]
Ok, closing then
