### ISSUE TITLE
Question about AudienceDomainOverride

### ISSUE THREAD

**Issue by msmolka** [Hawxy/Auth0Net.DependencyInjection#15]
I'm using Auth0 api also as authorization audience. Allowing setting only domain part of audience requires to set the value twice. I need to set in config domain only for AudienceDomainOverride value and another one for audience to use in authorization handler.

It would be good to have additionally option to set full audience here. E.g Simple Audience in Auth0Confinfiguration instead of Domain Override. Just use separate values for both.

**Comment by Hawxy** [comment]
You can use the full audience value there, the naming is just bad as it was implemented in a bit of a rush due to our systems requiring it when we enabled custom domains. I'll rename the property in the next major release.

**Comment by msmolka** [comment]
Ok
