### ISSUE TITLE
Add IServiceProvider as an input to AddAuth0AuthenticationClient

### ISSUE THREAD

**Issue by JasonWeinzierl** [Hawxy/Auth0Net.DependencyInjection#19]
It would be nice to have IServiceProvider available to fetch other services for populating configuration.

```
services.AddAuth0AuthenticationClient((config, provider) => {
    var configuration = provider.GetRequiredService<IConfiguration>();

    config.Domain = configuration["AUTH0_DOMAIN"];
    // etc.
});
```

**Comment by Hawxy** [comment]
Adding the overload isn't a big deal so I'll throw it into the next version, but `IConfiguration` is already readily available via `*ApplicationBuilder`/`Startup.cs`, which would be accessible to wherever this is being called.
