### ISSUE TITLE
.NET 8

### ISSUE THREAD

**Issue by pinkfloydx33** [Hawxy/Auth0Net.DependencyInjection#21]
Will you be adding/can you add a net8.0 target framework?

**Comment by Hawxy** [comment]
I will at some point. Are you running into any problems under .NET 8? The package should continue to work fine.

**Comment by pinkfloydx33** [comment]
Not yet... we're in the process of upgrading and I've been reviewing our dependencies. The multi-targeting of the MS.Extensions packages will cause the 7.x versions to get pulled in, unless I explicitly add them as direct dependencies to my project using the 8.x version (which I'd prefer not to do). If I reference something else with a dependency on any of those packages--for example, EF Core 8--then some of them may get bumped to v8 while others stay on v7.

Typically this _shouldn't_ be an issue assuming the SDK will roll everything forward, and no API surface has changed, etc... but I'm not sure that's a guarantee. We've hit issues in the past with mix-and-match MS.Extensions versions that didn't appear until runtime. I'm trying to get out ahead of it 🦺

**Comment by Hawxy** [comment]
No worries, I'll push out a new release in the next few days.
