### ISSUE TITLE
Auth0Net.DependencyInjection.3.2.0 has a dependency to Microsoft.Extensions.Caching.Memory.8.0.0 for all target frameworks

### ISSUE THREAD

**Issue by stevenvolckaert** [Hawxy/Auth0Net.DependencyInjection#26]
Thank you for the recent release of `Auth0Net.DependencyInjection.3.2.0`. I've noticed this version has a dependency to `Microsoft.Extensions.Caching.Memory.8.0.0` for all target frameworks.

This forces us to update all our `Microsoft.Extensions.*` dependencies to `8.*`, which I tried today, but the problem is that some of our applications are running on `netcoreapp3.1` which cannot be migrated easily, and that the `Microsoft.Extensions.*.8.*` packages haven't been tested with this target framework.

The compiler is showing warnings like

> Microsoft.Extensions.DependencyInjection.Abstractions 8.0.1 doesn't support netcoreapp3.1 and has not been tested with it. Consider upgrading your TargetFramework to net6.0 or later. You may also set <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings> in the project file to ignore this warning and attempt to run in this unsupported configuration at your own risk.

If the `Auth0Net.DependencyInjection` target frameworks

- `netstandard2.0` and `net6.0` would depend on `Microsoft.Extensions.Caching.Memory.6.0.1`;
- `net7.0` would depend on `Microsoft.Extensions.Caching.Memory.7.0.0`; and
- `net8.0` would depend on `Microsoft.Extensions.Caching.Memory.8.0.0`,

I think this would solve the issue?

Please let me know what you think. And I'd be happy to assist and make a pull request for this.

**Comment by Hawxy** [comment]
> I think this would solve the issue?

This isn't an option. FusionCache, our caching provider, does not support anything under 8.0.0. 

.NET Core 3.1 has been end of life for almost 1.5 years, and it's not the responsibility of open source maintainers to continue supporting it. This is tech debt that you need to solve as a company.

**Comment by Hawxy** [comment]
@stevenvolckaert Just something I realized, you'd be able to use `v1.7.0` of this package with .NET Core 3.1. The API is almost identical in that version, although you'd need to inject `ManagemantApiClient` instead of the interface.

**Comment by stevenvolckaert** [comment]
Thank you for this tip @Hawxy, much appreciated. I'll certainly try this out! 👍
